### ISSUE TITLE
Issue running?

### ISSUE THREAD

**Issue by vlall** [Dallinger/Dockerfiles#1]
@witekdev, with your branch, I can start and the stop compose without errors. But running `dd_run.py` gives me this:

````
$ python dd_run.py

Error getting IP address: Host is not running
dockercompose_redis_1 is up-to-date
dockercompose_postgresql_1 is up-to-date
dockercompose_dallinger_1 is up-to-date

======================
 Dallinger is running 
======================

 =  If you need to manually stop this script before it has completed:  =
 =  Please run "docker-compose stop" before running this script again  =
 =  This is to clean out any unfinished running experiments.           =

 Use CONTRL-C to stop this script 

bash: -c: line 0: syntax error near unexpected token `&'
bash: -c: line 0: `docker-compose logs dallinger |& tee log_dallinger.txt'
Traceback (most recent call last):
  File "dd_run.py", line 96, in <module>
    output = subprocess.check_output(['bash','-c', command])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '-c', 'docker-compose logs dallinger |& tee log_dallinger.txt']' returned non-zero exit status 2````

**Comment by witekdev** [comment]
This has been addressed.
